### ISSUE TITLE
docker-compose with blazegraph

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#156]
Adapt docker-compose to use blazegraph instead of jena-fuseki as a triplestore

**Comment by ingoboerner** [comment]
```
(:~
 : Clear graph in Blazegraph
 :)
declare function drdf:blazegraph-clear-graph($corpusname as xs:string) {
  let $url := $config:triplestore-server || "/bigdata/update"
  let $graph := "http://dracor.org/" || $corpusname
  let $log := util:log-system-out("clearing blazegraph graph: " || $graph)
  let $request :=
    <hc:request
      method="post"
    >
      <hc:body media-type="application/sparql-update" method="text">
        CLEAR SILENT GRAPH &lt;{$graph}&gt;
      </hc:body>
    </hc:request>

  let $response := hc:send-request($request, $url)

  return if ($response/@status = "204") then (
    util:log("info", "Cleared graph <" || $graph || ">"),
    true()
  ) else (
    util:log("warn", "Failed to clear graph <" || $graph || ">: " || $response/message),
    false()
  )
};
```

```
(:~
 : Send RDF data to Blazegraph
 https://github.com/dracor-org/dracor-api/issues/156
 :)
declare function drdf:blazegraph($uri as xs:anyURI) {
  let $corpus := tokenize($uri, "/")[position() = last() - 1]
  let $url := $config:triplestore-server || "/bigdata/sparql" || "?context-uri=" || encode-for-uri("http://dracor.org/" || $corpus)
  let $rdf := doc($uri)
  let $request :=
    <hc:request method="post" href="{ $url }">
      <hc:body media-type="application/rdf+xml">{ $rdf }</hc:body>
    </hc:request>
  let $response :=
      hc:send-request($request)
  let $status := string($response[1]/@status)
  return
      switch ($status)
          case "200" return true()
          case "201" return true()
          default return (
              util:log("info", "unable to store to blazegraph: " || $uri),
              util:log("info", "response header from blazegraph: " || $response[1]),
              util:log("info", "response body from blazegraph: " || $response[2]))
};
```

in config.xqm:

```
declare variable $config:triplestore-server := "http://blazegraph:8080";
```

don't know, but works only with `:8080`

also change the compose:

```
services:
  api:
    image: "dracor/dracor-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TRIPLESTORE_SERVER=blazegraph:8080
        - METRICS_SERVER=metrics:8030
    ports:
      - "8080:8080"
    volumes:
      - .:/tmp/export
    depends_on:
      - blazegraph
      - metrics
    links:
      - metrics
      - blazegraph
  blazegraph:
    image: "lyrasis/blazegraph:2.1.5"
    ports:
      - "8889:8080"
    expose:
      - "8889"
  metrics:
    build: https://github.com/dracor-org/dracor-metrics.git#main
    ports:
      - "8030:8030"
```
added `links`!

in load.xqm change:
```
(: clear fuseki graph :)
            (: drdf:fuseki-clear-graph($name), :)
            
            (: clear blazegraph graph :)
            drdf:blazegraph-clear-graph($name),
```

in function drdf:update in the `rdf.xqm`:
```
xmldb:store($collection, $resource, $rdf) => xs:anyURI() => drdf:blazegraph()
```

(sorry, don't know, why I can't push my local branch...)
