### ISSUE TITLE
local docker exist-db password

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#199]
Can I control which password is set when building/running a local docker 
currently the password is set to a random password value
```
stable-dracor-api-1       | no admin password provided
stable-dracor-api-1       | setting password to RHRQCVLfirAm2HhSJ5h7mBqn
```
I can not find an environment variable I could use to set the password. Is there a way to do so?

**Comment by ingoboerner** [comment]
just found it
```
services:
  api:
    environment:
      - EXIST_PASSWORD=
```
