### ISSUE TITLE
Swagger Editor reports error in OpenAPI components.schemas.SourceInPlayMetadata

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#310]
Swagger Editor reports an error in the OpenAPI:

> Structural error at components.schemas.SourceInPlayMetadata.required should NOT have fewer than 1 items

```
SourceInPlayMetadata:
      # see dutil:get-source
      type: object
      properties:
        name:
          # ontology: #play_digital_source_name
          type: string
          nullable: true
        url:
          # ontology: #play_digital_source_url
          type: string
          format: url
          nullable: true
      # currently neither name nor url is required, but we omit the source
      # object if none of the properties is available
      required: []
```

Removing "required" key fixes it
